package Acme::CPANLists::Import::PerlAdvent::2001_12_17;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2001/17th/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Attribute::TieClasses"}],summary=>"Modules mentioned in Perl Advent Calendar 2001 (day 17)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2001 (day 17)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2001/17th/> (retrieved on 2016-11-07). Visit the URL for the full contents.

