package Acme::CPANLists::Import::PerlAdvent::2001;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2001/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Mail::Audit"},{module=>"Mail::ListDetector"},{module=>"Tie::DBI"},{module=>"File::Spec"},{module=>"XML::XPath"},{module=>"Acme::Pony"},{module=>"Scalar::Util"},{module=>"List::Util"},{module=>"GraphViz"},{module=>"Test::More"},{module=>"POE"},{module=>"POE::Component::Client::HTTP"},{module=>"Crypt::Solitaire"},{module=>"Spreadsheet::WriteExcel"},{module=>"Pod::Coverage"},{module=>"Tie::Hash::Cannabinol"},{module=>"Attribute::TieClasses"},{module=>"Attribute::Overload"},{module=>"Class::Accessor::Chained"},{module=>"Class::MethodMaker"},{module=>"ExtUtils::ModuleMaker"},{module=>"Exporter::Simple"},{module=>"Text::Autoformat"},{module=>"Inline::Files"},{module=>"Quantum::Superpositions"},{module=>"Parse::RecDescent"}],summary=>"Modules mentioned in Perl Advent Calendar 2001"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2001

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2001/> (retrieved on 2016-11-07). Visit the URL for the full contents.

